spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/canonical_db
    username: postgres
    password: root@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

server:
  port: 8085

# File processing configuration
file:
  processing:
    threads: 5  # Number of concurrent threads for file processing

input:
  directory: ./input
